#!/usr/bin/env bash
set -e

echo install neovim
#Download latest neovim appimage
echo download neovim appimage
wget "https://github.com/neovim/neovim/releases/download/v0.10.2/nvim.appimage"

#Install nvim
echo configure appimage
chmod u+x nvim.appimage
./nvim.appimage --appimage-extract
ln -s /squashfs-root/usr/bin/nvim /usr/local/bin/nvim

#Install lazyvim
echo download lazyvim into configuration
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

#Clone setup repo for python
echo download lazyvim dotfiles
git clone https://github.com/omiethescientist/lazyvim-python-setup.git
cp lazyvim-python-setup/code/plugins/*.lua ~/.config/nvim/lua/plugins/
cp lazyvim-python-setup/code/config/*.lua ~/.config/nvim/lua/config/
cp lazyvim-python-setup/code/tmux.conf ~/.tmux.conf
rm -rf lazyvim-python-setup
